### ISSUE TITLE
Subclassing duplicates test cases

### ISSUE THREAD

**Issue by txels** [datadriventests/ddt#1]
Subclasses of ddt-decorated test cases generate duplicate tests

**Comment by davidsoncasey** [comment]
Is this still an issue? I was just taking a look at it and unable to replicate. Just stumbled across your project last week and found it useful so I thought I'd try to help out a bit.

**Comment by txels** [comment]
Thanks for your offer :)

Yes this is still an issue, if you feel like giving it a go. I can suggest some test case, but I believe it is fairly easy to reproduce.

**Comment by davidsoncasey** [comment]
Here's the test case I came up with to replicate:
```python
@ddt
class BaseTestCase(unittest.TestCase):

    @data(3, 4)
    def test_larger_than_two(self, value):
        self.assertTrue(larger_than_two(value))

    @data(0, 1)
    def test_not_larger_than_two(self, value):
        self.assertFalse(larger_than_two(value))

@ddt
class SubTestCase(BaseTestCase):

    @data(5, 6)
    def test_larger_than_two(self, value):
        self.assertTrue(larger_than_two(value))
```
This gives the base class the following tests:
* test_larger_than_two_1_3
* test_larger_than_two_2_4
* test_not_larger_than_two_1_0
* test_not_larger_than_two_2_1

From this, I would expect the subclass to have tests:
* test_larger_than_two_1_5
* test_larger_than_two_2_6
* test_not_larger_than_two_1_0
* test_not_larger_than_two_2_1

While it actually has tests:
* test_larger_than_two_1_3
* test_larger_than_two_1_5
* test_larger_than_two_2_4
* test_larger_than_two_2_6
* test_not_larger_than_two_1_0
* test_not_larger_than_two_2_1

I can see the problem with duplicating the index of the tests, I'm wondering, do you expect to only have the test cases from the subclass values (testing 5 and 6 are inherited from two) or do you expect that these tests are __added__ to the test_larger_than_two methods defined in the base class? I think that the former seems more natural to me, although I can see either making sense.

**Comment by pradyunsg** [comment]
I think the former should be default and the latter should be opt-in.

Also, because DRY, it should be possible to add data for a test without duplication of the method.

**Comment by Ogaday** [comment]
I think this behaviour should be expected, given inheritance rules. One way to avoid the repeated tests across classes is simply to have `SubTestCase` instead of BaseTestCase inherit from `unittest.TestCase`.

    @ddt
    class BaseTestCase(): 
        @data(3, 4)
        def test_larger_than_two(self, value):
            self.assertTrue(larger_than_two(value))
    
        @data(0, 1)
        def test_not_larger_than_two(self, value):
            self.assertFalse(larger_than_two(value))
    
    @ddt
    class SubTestCase(unittest.TestCase, BaseTestCase):
        @data(5, 6)
        def test_larger_than_two(self, value):
            self.assertTrue(larger_than_two(value))
