### ISSUE TITLE
sdist is missing `tox.ini`

### ISSUE THREAD

**Issue by mtelka** [datadriventests/ddt#113]
I'm packaging `ddt` for OpenIndiana and during packaging we run tests.  ~~Before tests are run we need to prepare environment to make sure everything needed is installed.  Testing requirements for `ddt` are listed in the [requirements/test.txt](https://github.com/datadriventests/ddt/blob/master/requirements/test.txt) file but the file is missing from sdist.  Please add `requirements/test.txt` to sdist to make downstream testing easier.~~

The sdist package at PyPI is missing `tox.ini`.  Please add the missing file to sdist.

Thank you.

**Comment by wswld** [comment]
@mtelka We don't use `tox` anymore and use GitHub actions for running tests and `flake8`. Is there a way you could work around that or `tox.ini` is absolutely neccessary? Are all other Python packages including `tox.ini`?

I was hoping to remove `tox.ini` completely as CI supports different versions out of the box. One could try setting up Github actions to run `tox` instead of doing it directly ([for example](https://stackoverflow.com/a/63682256)), but I don't have resources to work on that at the moment. If you have time to provide a PR I will look at it.

**Comment by mtelka** [comment]
> @mtelka We don't use `tox` anymore and use GitHub actions for running tests and `flake8`. Is there a way you could work around that or `tox.ini` is absolutely neccessary?

No, it is not necessary.  Since there is `tox.ini` in git I assumed you use it.  If you do not use it then I'd expect there is no `tox.ini` in git.

> Are all other Python packages including `tox.ini`?

Not all, but many.

> I was hoping to remove `tox.ini` completely as CI supports different versions out of the box. One could try setting up Github actions to run `tox` instead of doing it directly ([for example](https://stackoverflow.com/a/63682256)), but I don't have resources to work on that at the moment. If you have time to provide a PR I will look at it.

I do not mind how exactly you test `ddt`.  Since there is `tox.ini` available then I just assumed you use `tox`.

If you do not want to use `tox` then I believe you should remove `tox.ini` from git.

OTOH, `tox` is best way how to test packages and how to automatically detect test dependencies.  There is no other standardized way (AFAIK) how to do that.

**Comment by wswld** [comment]
@mtelka Hi Marcel,

Could you please provide an example of a package that include `tox.ini` in sdist? I switched Github actions to using `tox.ini`, but can't find examples of how `tox.ini` could be packaged.

**Comment by mtelka** [comment]
It looks like you use `setuptools` as a build backend so the documentation is here: https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html

Example of packages that use `setuptools` as a build backend and package `tox.ini` in sdist: setuptools, pytest.

**Comment by wswld** [comment]
@mtelka could you please check if 1.7.2 fixed the issue for you?

**Comment by mtelka** [comment]
> @mtelka could you please check if 1.7.2 fixed the issue for you?

Yes, it does.  Thank you for the fix!
