### ISSUE TITLE
1.7.0: `flake8` reports `pycodestyle` errors

### ISSUE THREAD

**Issue by mtelka** [datadriventests/ddt#114]
I see following `pycodestyle` errors when I run `flake8` for `ddt 1.7.0`:
```
ddt.py:43:80: E501 line too long (89 > 79 characters)
ddt.py:56:80: E501 line too long (81 > 79 characters)
ddt.py:179:80: E501 line too long (85 > 79 characters)
ddt.py:326:80: E501 line too long (80 > 79 characters)
ddt.py:424:80: E501 line too long (111 > 79 characters)
ddt.py:450:80: E501 line too long (118 > 79 characters)
ddt.py:451:80: E501 line too long (116 > 79 characters)
ddt.py:458:80: E501 line too long (117 > 79 characters)
ddt.py:461:80: E501 line too long (80 > 79 characters)
ddt.py:464:80: E501 line too long (112 > 79 characters)
test/test_functional.py:122:53: E231 missing whitespace after ','
test/test_functional.py:140:1: W293 blank line contains whitespace
test/test_functional.py:203:80: E501 line too long (81 > 79 characters)
test/test_functional.py:226:80: E501 line too long (82 > 79 characters)
test/test_functional.py:248:80: E501 line too long (82 > 79 characters)
test/test_functional.py:274:80: E501 line too long (81 > 79 characters)
test/test_named_data.py:66:1: W391 blank line at end of file
```

**Comment by wswld** [comment]
We have custom config for Flake8 when we run it https://github.com/datadriventests/ddt/blob/master/.github/workflows/pythonpackage.yml#L34C48-L34C48
Line length is set up to `--max-line-length=127`

**Comment by wswld** [comment]
On the other hand `exit-zero` means that most errors are effectively ignored, I will have a look at it

**Comment by mtelka** [comment]
> We have custom config for Flake8 when we run it https://github.com/datadriventests/ddt/blob/master/.github/workflows/pythonpackage.yml#L34C48-L34C48 Line length is set up to `--max-line-length=127`

Please update `tox.ini` accordingly (or simply remove `flake8` call from it).

Thank you.

**Comment by wswld** [comment]
@mtelka I've created #116 and I think fixed most of the issues there, could you please confirm that these has been fixed for you?

**Comment by mtelka** [comment]
I'm happy to report that with #116 in place all issues reported above are no longer reproducible.  Thank you.
