### ISSUE TITLE
1.7.0: Has Python 2.7 classifiers but is Python 3+ only.

### ISSUE THREAD

**Issue by alexdutton** [datadriventests/ddt#115]
The 1.7.0 release [adds async/await syntax](https://github.com/datadriventests/ddt/blob/82b169339552a3a837a60e9fa19ffff5ede8e603/ddt.py#L220) but the [Python 2 classifiers](https://github.com/datadriventests/ddt/blob/82b169339552a3a837a60e9fa19ffff5ede8e603/setup.py#L22-L23) haven't been removed from the distribution metadata.

So that clients resolving for Py 2.7 don't pick the wrong release, would you be able to remove the Python 2 classifiers, make a new release, and yank the 1.7.0 version from PyPI?

**Comment by wswld** [comment]
Good catch!
Thanks for letting me know, I will have a look at this ASAP

**Comment by wswld** [comment]
@alexdutton I have bumped the version to 1.7.1 and yanked 1.7.0
Thank you for pointing out the issue
