### ISSUE TITLE
Allow unpacking test data tuples into multiple arguments to the test case

### ISSUE THREAD

**Issue by txels** [datadriventests/ddt#3]
Right now, if you want to pass several arguments to your test, you typically provide a tuple for each test case, and have to unpack them inside the test method, such as:

``` python
@data((1,2,3), (4,5,9))
def test_things_with_3_numbers(self, arg):
    op1, op2, addition = arg
    ...
```

A nice improvement could be if `ddt` did this unpacking for you:

``` python
@packed_data((1,2,3), (4,5,9))
def test_things_with_3_numbers(self, op1, op2, addition):
    ...
```

**Comment by arnm** [comment]
I believe this could be enhanced further. [TestNG's @DataProvider](http://testng.org/doc/documentation-main.html#parameters-dataproviders) is what this really should be.

I really would like to do somethings like this:

```python
def get_data():
    return ( (1, 2), (2, 3,), )

@ddt
class TestMe(unittest.TestCase):
    @unpack
    @data(get_data())
    def test_func(self, first, second):
        # each tuple in the returned tuple is unpacked
        pass
````

I want more control of what data is passed into the test. Being able to generate all inputs for a test programmatically from a function, like TestNG does, would be a great way to go.

**Comment by viswagb** [comment]
@arnm is your above comments any progress, im too looking same..in ddt
