### ISSUE TITLE
@ddt to allow noindex test names

### ISSUE THREAD

**Issue by mmarek** [datadriventests/ddt#47]
As in subject. I would like to add parameter to @ddt decorator.

`@ddt(noindex=True)`

Behaviour would be fairly straightforward. It would prevent indexing names.
Thus resulting in naming generated functions with only name and data.
My use case is that I need more control over namings as I use test results in another system which is very difficult since names loose uniqueness. I can guarantee uniqueness of data fed through decorator.

Ideal aproach would probably be poviding in parameter a template string to be interpolated during creation of test names, but I am not certain if that effort would be well received.
Underneath more codified explanation.

```
@unpack
@data([('a', 'b'), ('c', 'd')])
def test_data(self, val1, val2)
```

would generate names:
```
test_data_a_b
test_data_c_d

```
instead of:
```
test_data_1_a_b
test_data_2_c_d
```

**Comment by wswld** [comment]
Hi,
Is this still relevant? Can you come up with a PR?

**Comment by mmarek** [comment]
I resolved it for my purposes and later switched to pytest :)

**Comment by wswld** [comment]
@mmarek OK as this is pretty specific and no longer needed I'm closing this. Have a nice day.
