### ISSUE TITLE
function ddt 

### ISSUE THREAD

**Issue by avvw** [datadriventests/ddt#64]
function ddt    test_docstring = getattr(v, "__doc__", None)，
when  v has attribte， return __doc__ of  v    So that desc of report  is __doc__ of v（list  tuple dict） ,not __doc__ of  testing function

**Comment by wswld** [comment]
Could you please elaborate. I'm not sure I understand the problem.

**Comment by wswld** [comment]
@avvw what do you think of the proposed resolution strategy? https://github.com/datadriventests/ddt/commit/0ab2fd9bdb17913b9d0b3a0cba697b4c1e1b1509#diff-44acb802320ed681ed514997cb5b5fa4R245
