### ISSUE TITLE
Generation of test case names fails in v1.2.0

### ISSUE THREAD

**Issue by jdiazdelrio** [datadriventests/ddt#65]
Hi there,

today, I have upgraded my DDT package to **v1.2.0** from **v1.1.3** and I have hit an issue when trying to run:

> nosetests -v test_convert.py

**In version 1.1.3** I used to get:

> test_01_format_code_1 (test_convert.TestConvert) ... ok

while with **version 1.2.0** I get:

> dict() -> new empty dictionary ... ok

I am using python v3.5.6 on a virtual environment. The test case looks like:

```
import unittest
from ddt import ddt, data, unpack

@ddt
class TestConvert(unittest.TestCase):

      @data({'title': 'Case 1: Nothing to do',
             'str_in': 'Hello world.',
             'str_out': 'Hello world.'})
      @unpack
      def test_01_format_code(self, title, str_in, str_out)
            # [ my code ]
            pass
```

**Comment by wswld** [comment]
Greetings. I'm on it, but it could take some time. If you have clear of the problem, could you please provide a pull request? It could speed up things immensely.

**Comment by wswld** [comment]
@jdiazdelrio what do you think of the proposed resolution strategy? https://github.com/datadriventests/ddt/commit/0ab2fd9bdb17913b9d0b3a0cba697b4c1e1b1509#diff-44acb802320ed681ed514997cb5b5fa4R246

**Comment by jdiazdelrio** [comment]
Hi @wswld,

the issue is only partially resolved. With this fix, the test case name is created, but it does not follow the previously existing strategy. For example, if we extend the test case I provided on my previous communication to

The test case looks like:

```
import unittest
from ddt import ddt, data, unpack

@ddt
class TestConvert(unittest.TestCase):

      @data(
            {'title': 'Case 1: Nothing to do',
             'str_in': 'Hello world.',
             'str_out': 'Hello world.'},
           {'title': 'Case 2: Still nothing to do',
             'str_in': 'Bye world.',
             'str_out': 'Bye world.'})
      @unpack
      def test_01_format_code(self, title, str_in, str_out)
            # [ my code ]
            pass
```

the result with this patch is:

> test_01_format_code ... ok
> test_01_format_code ... ok

when, at least, it should be something like:

> test_01_format_code_1 ... ok
> test_01_format_code_2 ... ok

Note that in the previous versions there was even more verbosity:
> test_01_format_code_1 (test_convert.TestConvert) ... ok
> test_01_format_code_2 (test_convert.TestConvert) ... ok

**Comment by wswld** [comment]
Hi! Thank you very much for your feedback. I'm now trying to understand
where the project should go and any user input is invaluable at this point.

As far as I understand, we agree on general test name resolution strategy,
but the implementation is far from ideal. I will look into it ASAP.

**Comment by wswld** [comment]
Hi, the issue seems to be fixed now.

**Comment by jdiazdelrio** [comment]
Hi @wswld 

I have upgraded DDT to this latest release and re-run my tests and it all works as expected.

Thank you so much for fixing this issue!

**Comment by wswld** [comment]
My pleasure. I'm glad it works now.
