### ISSUE TITLE
Test Case Ordinal Numbering zero-pads poorly

### ISSUE THREAD

**Issue by dambroc1** [datadriventests/ddt#75]
When using the @data decorator, DDT attempts to dynamically determine the zero-padding. The problem is, a global value is being set (index_len) for each test that calls @data. But the value index_len is not used until all tests have been added. Meaning only the index_len of the last test in the suite is used. If I have test A that has 300 data sets, and test B that has 2 data sets, no zero padding will occur in the test name.

This is also making existing test names change if new tests or new data sets are added in the future.

I would suggest remove the zero-padding index_len altogether to avoid dynamic test case name changes. But if not, then index_len should use the max of all test cases that call @data and not just the last one

**Comment by wswld** [comment]
@dambroc1 it took us some time to get there, but this issue seems to be fixed now.
